### ISSUE TITLE
[Style] Logo above menu is too big on mobile devices

### ISSUE THREAD

**Issue by dgomesbr** [awslabs/aws-well-architected-labs#108]
Please consider using 128px or less for the current logo. It does use a lot of space both on desktop and specially mobile.

**Comment by setheliot** [comment]
This is what I see on mobile.  Is this what you are referring to? 
![image](https://user-images.githubusercontent.com/3674210/84223698-7187ec80-aa8f-11ea-8205-3c0aabc0d6bf.png)

**Comment by dgomesbr** [comment]
Correct!
