### ISSUE TITLE
Error in item 3 - 1_lambda_iam_cleanup.md

### ISSUE THREAD

**Issue by wilmerl1** [awslabs/aws-well-architected-labs#120]
Hello,

It is to report that in the following route, the document has an error in item 3, the command to prepare the package with SAM no longer comes.

aws-well-architected-labs/content/Security/200_Labs/200_Automated_IAM_User_Cleanup/1_lambda_iam_cleanup.md

--------------
Run the following command to prepare your deployment package:
--------------

But there is no command.

Thanks!

**Comment by ByronPogson** [comment]
Thanks for pointing that out @wilmerl1, I've just pushed a fix to replace the missing line now.
