### ISSUE TITLE
Improvement: Use tags for for more straightforward tear down

### ISSUE THREAD

**Issue by rbakhshi** [awslabs/aws-well-architected-labs#14]
The "Tag" section on each guide can encourage use of them for better asset management.
In this case (running labs) we can use them to mark resources created during the lab and tear them down later more quickly.

**Comment by benjipotter** [comment]
Thank you @rbakhshi we'll incorporate tags in the labs

**Comment by benjipotter** [comment]
For some time now we have recommended using tags, in particular when creating CloudFormation stacks, like: https://www.wellarchitectedlabs.com/security/200_labs/200_automated_deployment_of_vpc/1_create_vpc_stack/
