### ISSUE TITLE
Level 200: Automated Deployment of VPC

### ISSUE THREAD

**Issue by AKANKSHAKSB** [awslabs/aws-well-architected-labs#149]
Stack Creation Failed using file :https://www.wellarchitectedlabs.com/Common/Create_VPC_Stack/Code/vpc-alb-app-db.yaml
Below is the error:
Cannot render the template because of an error.: YAMLException: unknown tag !<!Cidr> at line 238, column 115: ... ubnets, !Ref VPCSubnetIPv4Size ]] ^

**Comment by setheliot** [comment]
Thank you @AKANKSHAKSB for your feedback.

I am unable to reproduce this issue.  Can you please provide more details about how you attempted to create the stack?  Was this in the AWS Console?  At what point did it give you this error?

Can you please attach a copy of the YAML template you used? (so we can check if it somehow has become corrupted)?

**Comment by setheliot** [comment]
Ah, I figured it out!

After loading the template, please be sure to click on *NEXT* and do NOT click on *View in Designer*

![image](https://user-images.githubusercontent.com/3674210/94189952-48357580-fe60-11ea-92af-ea7a4389d707.png)

**Comment by AKANKSHAKSB** [comment]
Exactly it is the issue with View in Designer.
Usually templates get rendered in the designer without any error but sometimes they don't like this one.But anyways thanks,if we skip view in designer and directly got to Next ,stack is created successfully.
