### ISSUE TITLE
Incorrect Instruction under section 3.3

### ISSUE THREAD

**Issue by hrider** [awslabs/aws-well-architected-labs#15]
3.3 Using Systems Manager Inventory to Track Your Instances
3. In the Setup Inventory screen, define targets for inventory:
i.Under Specify targets by, select Specifying a tag
ii.Under Tags specify Environment for the key and OELab2018 for the value

Tag value is inconsistent with the cloudformation stack due to which systems manager was not gathering inventory.

**Comment by crlsonb** [comment]
Updated documentation to reference the correct tag: OELabIPM.  Thanks for the feedback!
