### ISSUE TITLE
Security - Level 200 AUTOMATED DEPLOYMENT OF WEB APPLICATION FIREWALL

### ISSUE THREAD

**Issue by Abhishekpathania01** [awslabs/aws-well-architected-labs#153]
In this lab, we have 2 exercises as below:
1. Configure AWS WAF
2. Configure Amazon CloudFront : here we have to deploy a distribution Step4. In Origin Domain Name enter the DNS or domain name from your elastic load balancer or EC2 instance but we didn't get any load balancer or EC2 instance when we deploy #1 CFT. 

CFT from #1 Configure AWS WAF  is not deploying any EC2 / load balancer or any other resources. Here is the URL to CFT: https://s3-us-west-2.amazonaws.com/aws-well-architected-labs/Security/Code/waf-global.yaml 

We do have load balancer deployment in 200 Level - Basic EC2 WAF Protection lab which comes after the lab Level 200 Automated Deployment of Web Application Firewall.

Guide URLs:
1. Configure AWS WAF: https://wellarchitectedlabs.com/security/200_labs/200_automated_deployment_of_web_application_firewall/1_config_waf/

2.  Configure Amazon CloudFront: https://wellarchitectedlabs.com/security/200_labs/200_automated_deployment_of_web_application_firewall/2_config_cloudfront/

We are hands on lab providers and working on onboarding all labs of Well architected labs, Could you please look into this issue ASAP? 

Thanks in Advance!
Abhishek

**Comment by Abhishekpathania01** [comment]
Hi @setheliot @benjipotter @natbesh ,

Thanks for looking into this issues, could you please give us an ETA if possible (just wanted to give an update to our clients on when the labs will be available for them to use).

Thanks,
Abhishek

**Comment by benjipotter** [comment]
Hi @Abhishekpathania01 apologies for the delay in responding and thank you for your feedback. The prerequisites really need updating - you do need something for CloudFront origin before you start the lab like a load balancer. I do plan to edit the WAF +CloudFront +WebApp labs so they are easier to follow however this will be in the next few months. When you say that one lab comes after another, please note that they are not in any order, except alphabetical. Also note the WAF solution is using v1 of the WAF not v2 and also needs updating. If you are lab providers and using them for income, perhaps you would like to contribute back to these open source labs using a pull request?
