### ISSUE TITLE
[Reliability] - Level 200: Testing for Resiliency of EC2 instances and Level 300: Testing for Resiliency of EC2, RDS, and AZ

### ISSUE THREAD

**Issue by Anmolkini** [awslabs/aws-well-architected-labs#158]
In "Level 200: Testing for Resiliency of EC2 instances" lab, we have 3 exercises as below,
-Deploy the Infrastructure and Application
-Configure Execution Environment
-Test Resiliency Using Failure Injection

In the above labs the user is asked to run "python fail_instance.py <vpc-id>" to  fail one of the EC2 instances in the "Test Resiliency Using Failure Injection" exercise.
The python/fail_instance.py does not work as expected.
Their seems to be an error in the fail_instance.py file. 

Lab guide link: (https://wellarchitectedlabs.com/reliability/200_labs/200_testing_for_resiliency_of_ec2/3_failure_injection/)

In "Level 300: Testing for Resiliency of EC2, RDS, and AZ" lab, we have seven exercises
-Deploy the Infrastructure and Application
-Configure Execution Environment
-Preparation for Failure Injection
-Test Resiliency Using EC2 Failure Injection
-Test Resiliency Using RDS Failure Injection
-Test Resiliency Using Availability Zone (AZ) Failure Injection
-Test Resiliency Using Failure Injection - Optional steps
In the above labs the user is asked to run "python fail_instance.py <vpc-id>" to  fail one of the EC2 instances in the "Test Resiliency Using EC2 Failure Injection" exercise.
The python/fail_instance.py does not work as expected.
Their seems to be an error in the fail_instance.py file. 

Lab guide link: [(https://wellarchitectedlabs.com/reliability/300_labs/300_testing_for_resiliency_of_ec2_rds_and_s3/4_failure_injection_ec2/)](https://wellarchitectedlabs.com/reliability/300_labs/300_testing_for_resiliency_of_ec2_rds_and_s3/4_failure_injection_ec2/)

**Comment by setheliot** [comment]
Hi @Anmolkini - thank you for your fedback?

You said 
> The python/fail_instance.py does not work as expected.
> Their seems to be an error in the fail_instance.py file.

I attempted to repro your issue, but it succeeds for me

```
$ python fail_instance.py vpc-0546b24ce1ff9b2a2
vpc-0546b24ce1ff9b2a2
Terminating instance:
i-060aed719448a1637
```

Can you please provide additional details about the error you are seeing?
What is output to console when you run the command?
What is the result in your AWS account?

**Comment by Anmolkini** [comment]
Hi @setheliot ,
We tried in BASH, Python and Powershell but we are facing the same issue saying,
Could not connect to the endpoint URL: "https://ec2.Ohio.amazonaws.com/"
Terminating
We have attached some screenshots below.
![issue-github1](https://user-images.githubusercontent.com/37663104/96443822-da942380-122a-11eb-8a14-17c4ec00de3e.png)
![issue-github](https://user-images.githubusercontent.com/37663104/96443836-e41d8b80-122a-11eb-8e5b-3b94bc3a263f.png)

**Comment by setheliot** [comment]
Hi Anmolkini, thank you for this additional data.  

For your AWS Region, you should use `us-east-2` instead of `Ohio`

Please re-visit and carefully follow the instructions for [Configure Execution Environment](https://wellarchitectedlabs.com/reliability/300_labs/300_testing_for_resiliency_of_ec2_rds_and_s3/2_configure_env/).  On that page  If you need help... then follow these instructions, which links to the following, which you will find helpful

https://wellarchitectedlabs.com/reliability/300_labs/300_testing_for_resiliency_of_ec2_rds_and_s3/documentation/aws_credentials/#cli

**Comment by Anmolkini** [comment]
Hi @setheliot 
Thanks you for the response, I got the required output when I used **us-east-2**.
The reason I used **Ohio** was because I got a suggestion saying **Ohio**
![githubissue](https://user-images.githubusercontent.com/37663104/96707210-32f72c80-13b5-11eb-86c7-f9530c414f9b.png)
Thank you for your help.
