### ISSUE TITLE
Level 300: Automated Athena CUR Query and E-mail Delivery

### ISSUE THREAD

**Issue by clueless101** [awslabs/aws-well-architected-labs#164]
In Section 2 
2. CREATE S3 BUCKET

The first step:
1. Login via SSO, go to the s3 dashboard and create an S3 bucket in the required region 

This is only possible (I'll assume) if the custom permissions JSON policy for the management_CostOptimization policy in lab "AWS Well-Architected Labs > Cost Optimization > 100 Labs > Level 100: AWS Account Setup: Lab Guide > ENABLE SINGLE SIGN ON (SSO)" has the permissions which would allow the creation of the bucket as part of the permission policy

The lab will succeed as presented only if you login as your Cost optimization account credentials and create the bucket as instructed and not using the SSO url and management creds. 

The sub account still has delegated access via the IAM policies to complete the lab successfully, just not using the SSO permissions. 

I'll accept this lab sequential logic was simply overlooked as part of the number of warnings about adhering to employing IAM principals of least privilege. 

Additionally during the Athena sections at no point instructions include designating the newly created bucket as part of the Athena query console settings. https://www.wellarchitectedlabs.com/cost/200_labs/200_4_cost_and_usage_analysis/2_setup_athena/

**Comment by natbesh** [comment]
Hi,
That is the challenge when updating the labs, there is some dependencies between them at times. This is the case as the account setup lab has moved to SSO & this lab has not been updated.
However the account setup lab provided for full access to s3 buckets as long as they have the prefix of "cost" - so you can use SSO as long as you use the correct bucket name. (i will be updating the lab soon)
Also - the lambda permissions re-write is no longer needed with the release of this feature: https://aws.amazon.com/blogs/aws/amazon-s3-update-three-new-security-access-control-features/  I have updated the account setup lab, again - i'll be updating this lab soon.

Thanks for the feedback!
