### ISSUE TITLE
CUR Split does not pull cost data for the last day of the month

### ISSUE THREAD

**Issue by cristian-popa** [awslabs/aws-well-architected-labs#165]
Need to revise the query https://github.com/awslabs/aws-well-architected-labs/blob/master/content/Cost/300_Labs/300_Splitting_Sharing_CUR_Access/3_athena_queries.md  to account for the fact that CUR data for the last day of the month can come in the first few days of the current month.

**Comment by cristian-popa** [comment]
Wondering if this is better, this would require the lambda to be modified as well to handle the last 2 months worth of data: 
`AND (year=CAST(year(current_date- INTERVAL '1' MONTH) AS VARCHAR))
             AND month=lpad(CAST(month(current_date- INTERVAL '1' MONTH) AS VARCHAR),2,'0')
        OR (year=CAST(year(current_date- INTERVAL '0' MONTH) AS VARCHAR))
             AND month=lpad(CAST(month(current_date- INTERVAL '0' MONTH) AS VARCHAR),2,'0')`

**Comment by natbesh** [comment]
Resolved with latest pull request
