### ISSUE TITLE
Improvement: further restrict IAM policy for S3

### ISSUE THREAD

**Issue by paulwakeford** [awslabs/aws-well-architected-labs#19]
Could the S3 section of the master 'Cost' policy be split out so it can be targeted to the specific bucket used for billing? Changing bucket policies and deleting policies for all buckets is a little wide ranging.

**Comment by natbesh** [comment]
Hi Paul Wakeford,
Sorry - which lab & policy are you referring to specifically?

**Comment by paulwakeford** [comment]
Ah sorry - this one: https://github.com/awslabs/aws-well-architected-labs/blob/master/Cost/Cost_Fundamentals/100_1_AWS_Account_Setup/README.md

**Comment by natbesh** [comment]
Paul,
Unfortunately not - its a chicken & the egg thing.  The lab creates the bucket, so you cant lock it down until it exists.
Its also explicitly called out to be removed from the user after the exercise is complete, for this reason.
