### ISSUE TITLE
http links that could be https

### ISSUE THREAD

**Issue by glb** [awslabs/aws-well-architected-labs#20]
It looks like there are a bunch of links to http://\[various places] that could be https links.

Would you accept a PR to fix them? What's the best way to make the change -- modify the Markdown files and then run `???` to generate the HTML in the `site` folder, or just do a global replace (I think the end results would be indistinguishable)?

**Comment by natbesh** [comment]
Hi glb,
The site folder is dynamically generated when we do code updates - so this would be continually overwritten.
We suggest that you enable http to https redirection, which will ensure that all serving is done securely, i.e. enabling redirect on your CloudFront distribution or webserver.

You can also view the labs via https here: http://wellarchitectedlabs.com

**Comment by glb** [comment]
I'm sorry, perhaps my original issue was unclear: I'm not looking to host a copy of this myself. 

Many of the links in the `wellarchitectedlabs.com` site are `http://` links instead of `https://` ... this isn't particularly safe, as even if your CloudFront distribution redirects (which it does), that's _after_ the initial HTTP connection, which could be intercepted.

If you look at the PR you'll see that the links can be fixed by updating the `site_url` and a variety of places in the Markdown source.
