### ISSUE TITLE
Getting "Message":"Failed Hydrating Credentials"

### ISSUE THREAD

**Issue by vvkvas** [awslabs/aws-well-architected-labs#218]
After both stacks are UP, getting below error while running command in Cloud9

```
cloud_user:~/environment $ ALBURL="patte-Patte-1AO1M7YY2EQAY-707364305.us-east-1.elb.amazonaws.com"
cloud_user:~/environment $ 
cloud_user:~/environment $ curl --header "Content-Type: application/json" --request POST --data '{"Name":"Andy Jassey","Text":"Welcome to ReInvent 2020!"}' $ALBURL/encrypt
{"Message":"Failed Hydrating Credentials"}cloud_user:~/environment $ 
cloud_user:~/environment $ 
cloud_user:~/environment $ curl -v --header "Content-Type: application/json" --request POST --data '{"Name":"Andy Jassey","Text":"Welcome to ReInvent 2020!"}' $ALBURL/encrypt                   
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 100.24.102.74...
* TCP_NODELAY set
* Connected to patte-Patte-1AO1M7YY2EQAY-707364305.us-east-1.elb.amazonaws.com (100.24.102.74) port 80 (#0)
> POST /encrypt HTTP/1.1
> Host: patte-Patte-1AO1M7YY2EQAY-707364305.us-east-1.elb.amazonaws.com
> User-Agent: curl/7.61.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 57
> 
* upload completely sent off: 57 out of 57 bytes
< HTTP/1.1 400 Bad Request
< Date: Sat, 09 Jan 2021 10:45:02 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 42
< Connection: keep-alive
< X-Powered-By: Express
< ETag: W/"2a-a+qdoISdZMp08hCMPddrtw4V/a0"
< 
* Connection #0 to host patte-Patte-1AO1M7YY2EQAY-707364305.us-east-1.elb.amazonaws.com left intact
{"Message":"Failed Hydrating Credentials"}cloud_user:~/environment $ 
```

What am I doing wrong?

**Comment by setheliot** [comment]
* Which lab?
* Which stack?
* you misspelled "Jassy" 😉

**Comment by aicode-demo** [comment]
I am getting the same issue, May I know what could be the problem?

**Comment by skinnytimmy** [comment]
Let me take a look now and I will see if I can reproduce the errors they are seeing.

**Comment by skinnytimmy** [comment]
> After both stacks are UP, getting below error while running command in Cloud9
> 
> ```
> cloud_user:~/environment $ ALBURL="patte-Patte-1AO1M7YY2EQAY-707364305.us-east-1.elb.amazonaws.com"
> cloud_user:~/environment $ 
> cloud_user:~/environment $ curl --header "Content-Type: application/json" --request POST --data '{"Name":"Andy Jassey","Text":"Welcome to ReInvent 2020!"}' $ALBURL/encrypt
> {"Message":"Failed Hydrating Credentials"}cloud_user:~/environment $ 
> cloud_user:~/environment $ 
> cloud_user:~/environment $ curl -v --header "Content-Type: application/json" --request POST --data '{"Name":"Andy Jassey","Text":"Welcome to ReInvent 2020!"}' $ALBURL/encrypt                   
> Note: Unnecessary use of -X or --request, POST is already inferred.
> *   Trying 100.24.102.74...
> * TCP_NODELAY set
> * Connected to patte-Patte-1AO1M7YY2EQAY-707364305.us-east-1.elb.amazonaws.com (100.24.102.74) port 80 (#0)
> > POST /encrypt HTTP/1.1
> > Host: patte-Patte-1AO1M7YY2EQAY-707364305.us-east-1.elb.amazonaws.com
> > User-Agent: curl/7.61.1
> > Accept: */*
> > Content-Type: application/json
> > Content-Length: 57
> > 
> * upload completely sent off: 57 out of 57 bytes
> < HTTP/1.1 400 Bad Request
> < Date: Sat, 09 Jan 2021 10:45:02 GMT
> < Content-Type: application/json; charset=utf-8
> < Content-Length: 42
> < Connection: keep-alive
> < X-Powered-By: Express
> < ETag: W/"2a-a+qdoISdZMp08hCMPddrtw4V/a0"
> < 
> * Connection #0 to host patte-Patte-1AO1M7YY2EQAY-707364305.us-east-1.elb.amazonaws.com left intact
> {"Message":"Failed Hydrating Credentials"}cloud_user:~/environment $ 
> ```
> 
> What am I doing wrong?

Firstly apologies for the late response. 

I notice that your end point address is in us-east-1 The lab needs to be run from ap-southeast-1 (Sydney). We did try and add a note to this effect in the introduction to the lab, but I will try and update to add a reminder in later points in the lab. Can you try and deploy all the stacks to ap-southeast-1 and let me know if this addresses your issue?

I will also update the lab to fix the spelling mistake with the example!

Please let me know how you go...if you are still experiencing issues, respond to this thread and we can arrange a quick debug session.

Thanks!

Tim

**Comment by benjipotter** [comment]
@skinnytimmy resolved this issue and should have been closed earlier
