### ISSUE TITLE
Security 200 Level error, with default setting, while used Cloud Formation Template

### ISSUE THREAD

**Issue by asifkhalil** [awslabs/aws-well-architected-labs#237]
https://wellarchitectedlabs.com/security/200_labs/200_automated_deployment_of_ec2_web_application/1_create_web_stack/
I have tried both the templates but getting same error. Screen shot file has been attached.

[AWS_SEC_200.docx](https://github.com/awslabs/aws-well-architected-labs/files/6106604/AWS_SEC_200.docx)

**Comment by benjipotter** [comment]
@asifkhalil just checking you saw the prerequisite to create the VPC first thats covered in https://www.wellarchitectedlabs.com/security/200_labs/200_Automated_Deployment_of_VPC/README.md

**Comment by benjipotter** [comment]
Closing, please contact with further information.
