### ISSUE TITLE
Security - LEVEL 200: BASIC EC2 WEB APPLICATION FIREWALL PROTECTION

### ISSUE THREAD

**Issue by midnight480** [awslabs/aws-well-architected-labs#260]
Please update AWS WAF URL at [This Section](https://wellarchitectedlabs.com/security/200_labs/200_basic_ec2_with_waf_protection/3_create_alb_with_waf/#32-configure-application-load-balancer-with-waf).

old URL:

`https://console.aws.amazon.com/waf/`

new URL:

`https://console.aws.amazon.com/wafv2/`

Note:

After access `https://console.aws.amazon.com/waf/` , receive http 404 error.

**Comment by benjipotter** [comment]
Thank you @midnight480 resolved in https://github.com/awslabs/aws-well-architected-labs/commit/cab6ade53909540c6fae91252dd5dbd38c0e413e
