### ISSUE TITLE
Cloudformation Desiger View Error - 200_Automated_Deployment_of_VPC

### ISSUE THREAD

**Issue by mojoa** [awslabs/aws-well-architected-labs#28]
For Lab 

[200_Automated_Deployment_of_VPC](https://wellarchitectedlabs.com/Security/200_Automated_Deployment_of_VPC/Lab_Guide.html)

CloudFormation Designer View Error:
8/16/2019, 8:39:11 AM - Cannot render the template because of an error.: YAMLException: duplicated mapping key at line 1410, column 3: Shared1NAT1EIP: ^

**Comment by saeed2402** [comment]
Any updates on this issue? I'm having the same problem.

**Comment by benjipotter** [comment]
The error with the latest template is on line 238, it appears to be related to using shorthand with a select, or the Cidr function. Suggestion would be to use a text editor to edit the template instead of Designer. Apologies for the inconvenience.
