### ISSUE TITLE
300_Incident_Response_with_AWS_Console_and_CLI

### ISSUE THREAD

**Issue by mojoa** [awslabs/aws-well-architected-labs#29]
Deny all policy still allows sts get-caller-identity to display information. This is not what one would expect as an incident response tactic and may need to be mentioned in the lab material.

2.2 Block access in AWS IAM
Blocking access to an IAM entity, that is a role, user or group can help when there is unauthorized activity as it **will no longer be able to perform any actions.**

``aws iam put-user-policy --user-name Bob --policy-name DenyAll --policy-document '{ "Statement": [ { "Effect": "Deny", "Action": "*", "Resource": "*" } ] }'``

`` aws sts get-caller-identity
{
    "UserId": "ZZZZZZZZZZZZZZZZZZZZZZ",
    "Account": "999999999999",
    "Arn": "arn:aws:iam::999999999999:user/Bob"
}``

**Comment by mojoa** [comment]
2.4.1 AWS Console
As a side note, it seems it may be worth mentioning in the LAB how to interpret the console view of the inline DenyAll policy, since it seems to indicate "Full access". The view also seems to indicate one of the 189 services was left out of the Explicit deny. This lead me to doubt.

![image](https://user-images.githubusercontent.com/42722456/63353113-4087d100-c330-11e9-9557-78e8bcabc7ad.png)
Then at the bottom it mentions **Allow (0 of 189 services)** 

![image](https://user-images.githubusercontent.com/42722456/63354387-58605480-c332-11e9-874c-0ecc44df7ac0.png)

**Comment by benjipotter** [comment]
Thank you @mojoa I have modified the notes, apologies for the delay.
