### ISSUE TITLE
200: Lab: Create Cost Intelligence Dashboard

### ISSUE THREAD

**Issue by cdtiwari-ebi** [awslabs/aws-well-architected-labs#294]
In my root(master) account there is no return row for saving plans and reserved instance so I created my views with last options. "Click here - if you do not have Reserved Instances, and do not have Savings Plans" 
All the views are created with above script only db_name.tablename updated as per instruction.

All the views created successfully and I can test them with limit of 10 record, next step to create dashboard cli. After running the command `aws --profile master --region eu-west-2 quicksight create-dashboard --cli-input-json file://quicksight_create-dashboard.json` There is no dashboard appears.

When I tried using describe command to check, I found an error in the Error section
```
"Errors": [
                {
                    "Type": "COLUMN_REPLACEMENT_MISSING",
                    "Message": "Required column 'ri_sp_end_date' is missing in data set 'arn:aws:quicksight:eu-west-2:<account_id>:dataset/<summary_view_hashmap_code>'"
                }
            ],

```
Why I am facing this issue? Could you please help?
hashmap reference match to summary_view from json i matched.

**Comment by aleewhitman** [comment]
thanks for reaching out. The ri_sp_end_date field is in the view. Can you please confirm you see that field in the limit 10 record preview in athena and that the joins were successfully created in the quicksight dataset?
