### ISSUE TITLE
Lab 200: 2. Modify Cost Intelligence Dashboard, Step 15 onwards Screens are not sync with latest UI version

### ISSUE THREAD

**Issue by cdtiwari-ebi** [awslabs/aws-well-architected-labs#295]
[When](URL) I was trying to overlay data. I wasn't able to follow all the instructions because screenshots are not synced with the latest UI of quicksight and less instruction is given.
While mapping account names, I always get `null` no account names are visible to my dashboard.

**Comment by aleewhitman** [comment]
Thanks for the feedback. We are currently in the process of updating this lab with the latest UI updates and best practices. We will have it updated in the coming weeks, but in the mean time I can gladly send the steps via email. Let me know a good email to send to you.

**Comment by cdtiwari-ebi** [comment]
> Thanks for the feedback. We are currently in the process of updating this lab with the latest UI updates and best practices. We will have it updated in the coming weeks, but in the mean time I can gladly send the steps via email. Let me know a good email to send to you.

**Comment by cdtiwari-ebi** [comment]
My mail id is cdtiwari@ebi.ac.uk
