### ISSUE TITLE
Bug in lambda-iam-user-cleanup.py for lab: security/200_labs/200_automated_iam_user_cleanup

### ISSUE THREAD

**Issue by ashish-logmaster** [awslabs/aws-well-architected-labs#306]
On page https://wellarchitectedlabs.com/security/200_labs/200_automated_iam_user_cleanup/1_lambda_iam_cleanup/  there is a reference to "lambda-iam-user-cleanup.py".   In that file, lines 33 and 41 have identical test which I think is a bug due to copy paste.

Line 41: 
`elif (minAgeUnusedUsersToDelete > 0 and daysSinceUsed >= minAgeUnusedUsersToDelete):`

I think it should be 
`elif (minAgeUnusedUsersToDelete > 0 and daysSinceUsed >= minAgeUnusedUsersToDisable):`

Sorry I could not find this file in github else would have filed it as a PR, please fix it.

**Comment by benjipotter** [comment]
Resolved in PR305
