### ISSUE TITLE
Lab steps need to correct

### ISSUE THREAD

**Issue by asif-khalil** [awslabs/aws-well-architected-labs#319]
![image](https://user-images.githubusercontent.com/64101506/127858925-2f32c4a3-f783-46fd-90ff-f6412b810ea3.png)
Lab steps ordering need to correct, Screenshot is attached

**Comment by sssalim-aws** [comment]
Fixed on Commit :
https://github.com/awslabs/aws-well-architected-labs/commit/444ea10b3981e15fd2e2bc55ac01a46c6a9978f0
Thanks for bringing this to our attention.
