### ISSUE TITLE
Disaster Recovery Module 1: Restore instructions discrepency

### ISSUE THREAD

**Issue by jmoldan** [awslabs/aws-well-architected-labs#324]
Looks like BackupAndRestore.yaml has been updated on https://wellarchitectedlabs.com/reliability/disaster-recovery/workshop_1/us-east-1-deployment/ - or is different than the lab instructions indicate. 

3.2 - There is no assetbucket

4.5 /home/ec2-user/DRImmersionDay/m2mcfg.sh does not exist.  Possibly /home/ec2-user/unishopcfg.sh ?

4.6 Path doesn't exist /home/ec2-user/DRImmersionDay/UniShopUI and /home/ec2-user/DRImmersionDay/UniShopLambda/build/libs

**Comment by setheliot** [comment]
Thanks... these labs are new, so there may be some bugs.  We'll take a look

**Comment by setheliot** [comment]
Ho @jmoldan, as you can see above, @rayzaman pulled a fix into master - let us know if this fixes your issue.  If not then please re-open this issue.
