### ISSUE TITLE
Level 200 - CloudFront with WAF Protection issues

### ISSUE THREAD

**Issue by DanielTatarkin** [awslabs/aws-well-architected-labs#33]
Lab Link: [https://wellarchitectedlabs.com/Security/200_CloudFront_with_WAF_Protection/Lab_Guide.html#1-launch-instance](url)

**1.** **Steps** **5.2** thru **5.7** are missing images
**2.** In **Step** **5.7**, provided user data script is missing new line characters that should seperate commands the 

**Screenshots:**

![image](https://user-images.githubusercontent.com/16328369/66274471-19884e80-e84d-11e9-9c32-96a4b7379306.png)

![image](https://user-images.githubusercontent.com/16328369/66274435-af6fa980-e84c-11e9-888b-a0747474e3e7.png)

**Comment by benjipotter** [comment]
Thank you @DanielTatarkin was markdown formatting error.
