### ISSUE TITLE
Terraform deployments

### ISSUE THREAD

**Issue by diepes** [awslabs/aws-well-architected-labs#333]
After looking through the Cloudformation templates (seems very verbose) i was wondering if there is any labs that use terraform or plans to support it in the future to deploy infrastructure ?

**Comment by awssteph** [comment]
Hi, some modules do such as:

- https://github.com/awslabs/well-architected-lab200-pricing-model-analysis-terraform-module
- https://github.com/awslabs/well-architected-lab300-aws-compute-optimiser-collector-terraform-module
- https://github.com/awslabs/well-architected-lab300-aws-compute-optimiser-collector-terraform-module

And we are developing more but which labs where you l specifically looking at?

**Comment by setheliot** [comment]
yes @diepes can you share which pillar you are looking at?

Also know that this is open source -- we do accept pull requests if you want to add to our labs

**Comment by setheliot** [comment]
@diepes which labs would you like to see terraform used for?

**Comment by setheliot** [comment]
no response. closing
