### ISSUE TITLE
Cloud Formation fails

### ISSUE THREAD

**Issue by tagoreghanta** [awslabs/aws-well-architected-labs#337]
Cloud formation failed at this step inspite of Admin privs and ensuring that all permissions are provided
Not enough logs to specific the error

AWSPutS3CURNotification 
CREATE_FAILED
 Received response status [FAILED] from custom resource. Message returned: See the details in CloudWatch Log Stream: 2021/08/17/....

Could you please suggest for additional logs

**Comment by setheliot** [comment]
Hi.  Which lab was this specifically?

**Comment by aleewhitman** [comment]
Hi! following up on Seth's ask, can you please confirm what lab this occurred in?

**Comment by awssteph** [comment]
Not heard back so closing issue
