### ISSUE TITLE
Instance type needs to be updated with latest Family

### ISSUE THREAD

**Issue by ag-cloudskills** [awslabs/aws-well-architected-labs#355]
t2 family is not available in ap-south-1c which is causing the Cloudformation to fail in ap-south1 ( region). Can you please get this addressed?

**Comment by setheliot** [comment]
@ag-cloudskills, which lab? 

Note that many labs have a CloudFormation parameter which allows you to change the instance type, which should get you around this problem

**Comment by setheliot** [comment]
closing as not actionable
