### ISSUE TITLE
Security 100 Labs: Create a Data Bunker Account: Instructions on Step 2 are not clear on which account to create the logs bucket in

### ISSUE THREAD

**Issue by mnylen** [awslabs/aws-well-architected-labs#38]
The Step 2 in Security 100: Create a Data Bunker Lab Guide does not mention that the bucket should be created in the newly created (Step 1) security account.

This is mentioned much later in Step 4.7.:

> Under Storage location, select No for Create new S3 bucket and instead select the bucket created in the security account created previously

**Comment by ByronPogson** [comment]
Added in instruction to switch into the newly created security account.
