### ISSUE TITLE
Possible Security Problems

### ISSUE THREAD

**Issue by ctindall** [awslabs/aws-well-architected-labs#41]
Hey there! I noticed some possible problems in some code in this repo. A quick summary of a few of them is below, but let me know if you're interested in seeing a full report or talking about cloud security in general.

---

**severity:** serious

**filename:** `./site/Security/200_Automated_Deployment_of_IAM_Groups_and_Roles/Code/baseline-iam.yaml`

**line number(s):** [304]

**resource(s):** 

IAM managed policy should not allow a * resource with PassRole action

---

**severity:** warning

**filename:** `./site/Security/200_Automated_Deployment_of_IAM_Groups_and_Roles/Code/baseline-iam.yaml`

**line number(s):** [66, 304, 377]

**resource(s):** 

IAM managed policy should not allow * resource

---

**severity:** warning

**filename:** `./site/Security/200_Automated_Deployment_of_IAM_Groups_and_Roles/Code/baseline-iam.yaml`

**line number(s):** [413]

**resource(s):** 

IAM role should not allow * resource on its permissions policy

---

**severity:** warning

**filename:** `./site/Security/200_Automated_Deployment_of_IAM_Groups_and_Roles/Code/baseline-iam.yaml`

**line number(s):** [113, 158, 215, 243, 368, 66, 167, 225, 282, 304, 316, 377, 122, 187, 251, 336, 413, 450, 474]

**resource(s):** 

Resource found with an explicit name, this disallows updates that require replacement of this resource

---

**severity:** warning

**filename:** `./site/Security/200_Automated_IAM_User_Cleanup/Code/cloudformation-iam-user-cleanup.yaml`

**line number(s):** [65]

**resource(s):** 

IAM role should not allow * resource on its permissions policy

---

**severity:** warning

**filename:** `./site/Security/200_Automated_Deployment_of_Detective_Controls/Code/cloudtrail-config-guardduty.yaml`

**line number(s):** [406, 435]

**resource(s):** 

Resource found with an explicit name, this disallows updates that require replacement of this resource

---

**severity:** warning

**filename:** `./site/Security/200_Automated_Deployment_of_Detective_Controls/Code/cloudtrail-config-guardduty.yaml`

**line number(s):** [259, 483]

**resource(s):** 

S3 Bucket should have encryption option set

**Comment by benjipotter** [comment]
Thank you for your issue and apologies for the delay! I've been through the policies in the CloudFormation template and where the action supports a resource other than * there are examples given. e.g. cloudformation:EstimateTemplateCost only supports resource *, where cloudformation:CreateStack does support stack name and that example is already given. In relation to explicit names, this is a tradeoff for this lab of using stack ID vs pretty names and we will call this out in future update soon.
