### ISSUE TITLE
200_labs - CloudFormation deployment - "Access denied for operation 'AWS::QuickSight::Dashboard'."

### ISSUE THREAD

**Issue by NK74** [awslabs/aws-well-architected-labs#437]
Hi,

I encountered an issue with the Cloudformation template for the "Level 200: Cloud Intelligence Dashboards"
https://wellarchitectedlabs.com/cost/200_labs/200_cloud_intelligence/cost-usage-report-dashboards/dashboards/2a_cost_intelligence_dashboard/

https://console.aws.amazon.com/cloudformation/home#/stacks/new?&templateURL=https://aws-well-architected-labs.s3.us-west-2.amazonaws.com/Cost/Labs/200-cloud-intelligence-dashboards/cid_cudos.yaml

Resource handler returned message: "Access denied for operation 'AWS::QuickSight::Dashboard'." (RequestToken: 153c3458-44f6-c52d-e36c-8b47851b964f, HandlerErrorCode: AccessDenied)

![image](https://user-images.githubusercontent.com/17825769/150827591-d7e881e2-f4f9-4c63-a7db-962208ebf0f1.png)

Anyone knows a workaround ?

**Comment by NK74** [comment]
Any news ?

**Comment by awssteph** [comment]
Hey, just checking do you have access to quicksight?

**Comment by aleewhitman** [comment]
Hi! Can you confirm you've completed the pre reqs? This will help us troubleshoot. 

https://wellarchitectedlabs.com/cost/200_labs/200_cloud_intelligence/cost-usage-report-dashboards/dashboards/1_prerequistes/

**Comment by aitorbenito** [comment]
Same error here.... Pre-reqs completed... Cloudformation is able to create the proper datasets in quicksight, but fails with the same error when trying to create the CUDOS dashboard :S
<img width="1480" alt="Captura de pantalla 2022-03-18 a las 11 37 03" src="https://user-images.githubusercontent.com/12656721/158988186-a54f8ba7-3b32-4df2-8437-03641b3a1c07.png">

**Comment by abjoerne** [comment]
You get this error if you do not have the enterprise subscription in Quicksight. The API returns "An error occurred (UnsupportedUserEditionException) when calling the CreateDashboard operation: CreateDashboard API is supported only for enterprise users" which is not returned to cloud-formation...

**Comment by aaronedell** [comment]
If you have Enterprise edition in Quicksight then the only other thing I can think of that might cause an access denied error is that your QuickSight identity region is different than the region you're deploying the CFN in.

**Comment by aaronedell** [comment]
It already mentions it here: https://wellarchitectedlabs.com/cost/200_labs/200_cloud_intelligence/cost-usage-report-dashboards/dashboards/1_prerequistes/#enable-quicksight
