### ISSUE TITLE
Cost 300_Optimization_Data_Collection : rightsizing-recommandation breaking update

### ISSUE THREAD

**Issue by Raphael-D-S** [awslabs/aws-well-architected-labs#457]
On file : [organization_rightsizing_lambda.yaml](https://github.com/awslabs/aws-well-architected-labs/blob/master/static/Cost/300_Optimization_Data_Collection/Code/organization_rightsizing_lambda.yaml)

On line [143](https://github.com/awslabs/aws-well-architected-labs/blob/6841957cc1c0c99b69d1fae763537d51f5cfc0ec/static/Cost/300_Optimization_Data_Collection/Code/organization_rightsizing_lambda.yaml#L143) : store_data_to_s3 function filesize check

A recent update broke the lambda execution: 

New version (execution without error but files not saved in S3 and function result as "Failed")

        def store_data_to_s3(data, s3client, path, filename):
            fileSize = os.path.getsize(f"/tmp/{filename}.json")
            if fileSize == 0:  
                print(f"No data in file for {DestinationPrefix}")
            else:
              today = date.today()
              year = today.year
              month = today.strftime('%m')
              day = today.day
              filepath = '/tmp/%s-%s' % (today, filename)
              with open(filepath, 'w') as f:
                  json.dump(data, f, default=str)
                  f.write('\n')
              upload_file_to_s3(s3client, BUCKET, filepath,
                                "%s/year=%s/month=%s/day=%s/%s-%s-%s-%s"
                                % (path, year, month, day, year, month, day, filename))

Previous working function :

        def store_data_to_s3(data, s3client, path, filename):
            today = date.today()
            year = today.year
            month = today.strftime('%m')
            day = today.day
            filepath = '/tmp/%s-%s' % (today, filename)
            with open(filepath, 'w') as f:
                json.dump(data, f, default=str)
                f.write('\n')
            upload_file_to_s3(s3client, BUCKET, filepath,
                            "%s/year=%s/month=%s/day=%s/%s-%s-%s-%s"
                            % (path, year, month, day, year, month, day, filename))

**Comment by awssteph** [comment]
Hey, so this check the size of the file and if 0 then the file is not uploaded. What were the file sizes before?

**Comment by awssteph** [comment]
Thank you for highlighting this, PR in to fix

**Comment by awssteph** [comment]
This has now been merged, please try and let us know if you have any other problems
