### ISSUE TITLE
New L300 Reliability Lab content using FIS

### ISSUE THREAD

**Issue by paulikeloa** [awslabs/aws-well-architected-labs#459]
I am working on content for the SG Summit using AWS Fault Injection Simulator. I am developing a follow-up on to https://wellarchitectedlabs.com/reliability/300_labs/300_testing_for_resiliency_of_ec2_rds_and_s3/ that will use FIS for the experiments instead of chaos scripts/cli.

**Comment by setheliot** [comment]
Hi Paul, setup time with me to talk
