### ISSUE TITLE
Cost 300_Optimization_Data_Collection :  Overuse of sts assume role in organization accounts

### ISSUE THREAD

**Issue by Raphael-D-S** [awslabs/aws-well-architected-labs#466]
On code : [OrganizationData from child accounts](https://github.com/awslabs/aws-well-architected-labs/blob/master/static/Cost/300_Optimization_Data_Collection/Code/)

Theses files :
- [300_Optimization_Data_Collection/Code/rds_util_template.yaml](https://github.com/awslabs/aws-well-architected-labs/blob/master/static/Cost/300_Optimization_Data_Collection/Code/rds_util_template.yaml)
- [300_Optimization_Data_Collection/Code/source/ecs/ecs.py](https://github.com/awslabs/aws-well-architected-labs/blob/master/static/Cost/300_Optimization_Data_Collection/Code/source/ecs/ecs.py)
- [300_Optimization_Data_Collection/Code/source/fof/ami.py](https://github.com/awslabs/aws-well-architected-labs/blob/master/static/Cost/300_Optimization_Data_Collection/Code/source/fof/ami.py)
- [300_Optimization_Data_Collection/Code/source/fof/ebs.py](https://github.com/awslabs/aws-well-architected-labs/blob/master/static/Cost/300_Optimization_Data_Collection/Code/source/fof/ebs.py)
- [300_Optimization_Data_Collection/Code/source/fof/snapshot.py](https://github.com/awslabs/aws-well-architected-labs/blob/master/static/Cost/300_Optimization_Data_Collection/Code/source/fof/snapshot.py)

Issue :
The sts assume role is currently called for each service and each region. A quick improvement could be to use a sts session and reuse it for each region.
Doing this sts calls will be reduced to only 1 for each service instead of one per region and per service.

**Comment by awssteph** [comment]
Hey, thank you for this PR I will review and get back to you ASAP :D

**Comment by awssteph** [comment]
Merged, thank you for your contribution
