### ISSUE TITLE
Cost 300_Optimization_Data_Collection : missing policy for rds_medrics Optimization-Data-Multi-Account-Role 

### ISSUE THREAD

**Issue by Raphael-D-S** [awslabs/aws-well-architected-labs#485]
On file : [Optimization_Data_Collector.yaml](https://github.com/awslabs/aws-well-architected-labs/blob/master/static/Cost/300_Optimization_Data_Collection/Code/optimisation_read_only_role.yaml)

On line [238](https://github.com/awslabs/aws-well-architected-labs/blob/08b207344972aced47b386499738eace10467687/static/Cost/300_Optimization_Data_Collection/Code/optimisation_read_only_role.yaml#L238) : I think there is a missing cloudwatch policy to get rds utilization metrics.

On file for line 286 we have that call : [rds_util_template.yaml](https://github.com/awslabs/aws-well-architected-labs/blob/08b207344972aced47b386499738eace10467687/static/Cost/300_Optimization_Data_Collection/Code/rds_util_template.yaml#L286)
Indeed, the rds_metrics calls boto3 cloudwatch client but there is no right for it in the assumed role on organization accounts

        {
            "Action": [
                "cloudwatch:GetMetricStatistics"
            ],
            "Resource": "*",
            "Effect": "Allow"
        },

**Comment by awssteph** [comment]
Thanks for the issue, we have a PR in. 
Steph
