### ISSUE TITLE
Cost 300_Optimization_Data_Collection : rds_util_template.yaml

### ISSUE THREAD

**Issue by Raphael-D-S** [awslabs/aws-well-architected-labs#497]
Hello, 

I noticed that the cloudwatch role was using the local boto3 client instead of using the session client.
Therefore, cloudwatch requests the local data instead of the rds account cloudwatch data

https://github.com/awslabs/aws-well-architected-labs/blob/80fee606c0405ad180d014c618cebd22932c5347/static/Cost/300_Optimization_Data_Collection/Code/rds_util_template.yaml#L332

This should be : 
 cwclient = session.client()

**Comment by awssteph** [comment]
Hey, so that change does not work. I believe that the 'Client' its referring too is the one 2 lines above? I did see that the one below is missing the session though. See Branch attached to this issue and let me know.

Thanks for feedback

**Comment by awssteph** [comment]
this has been resolved
