### ISSUE TITLE
300: Automated Athena CUR Query and E-mail Delivery : An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: line 1:190

### ISSUE THREAD

**Issue by NK74** [awslabs/aws-well-architected-labs#502]
Hello,

I followed the [instructions](https://wellarchitectedlabs.com/cost/300_labs/300_automated_cur_query_and_email_delivery/), however I got an issue when i try to execute my Lamdba Function step...

```

{
"errorMessage": "An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: line 1:190: 
mismatched input '.xxxxxxxxxxxx'. Expecting: ',', '.', 'AS', 'CROSS', 'EXCEPT', 'FOR', 'FULL', 'GROUP', 'HAVING', 'INNER', 'INTERSECT', 'JOIN', 'LEFT', 'LIMIT', 'NATURAL', 'OFFSET', 'ORDER', 'RIGHT', 'TABLESAMPLE', 'UNION', 'WHERE', <EOF>, <identifier>",

```
![image](https://user-images.githubusercontent.com/17825769/161297193-7a7eb828-419d-4f32-89c5-a3502660b083.png)

**config.yml**
```
#S3 location for athena cur query results temp storage
#Don't miss '/' at the end of path 
#Make sure your Lambda role has write/read permission to this path
CUR_Output_Location: s3://athena-billing-xxxxxxxxxxxx/

#CUR database name and table
CUR_DB: "athenacurcfn_xxxxxxxxxxxx_c_u_r_hourly_athena.xxxxxxxxxxxx_cur_hourly_athena"

#CUR file name with suffix '.xlsx', which is sent as attachment via SES
CUR_Report_Name: 'cost_utilization_report.xlsx'

#SES configuration
Region: eu-west-1
Subject: 'Cost and Utilization Report'
#i.e. 'john@example.com'
Sender: '*********@mail.xyz'
#If there are mulitple recipients, seperate them by commas. i.e. 'john@example.com,alice@example.com'
Recipient: '*********@mail.xyz'
#Mail body
Body_Text: "Hi,

Please find your Cost Utilization Report attached:
..........

"
```

I tried the Athena query by enabling the debug mode :

> SELECT year, month(line_item_usage_start_date) month, product_product_name AS "Product_Name", sum("line_item_unblended_cost") AS "Cost($)" FROM athenacurcfn_xxxxxxxxxxxx_c_u_r_hourly_athena.xxxxxxxxxxxx_cur_hourly_athena WHERE (year='2022' AND month='4') OR (year='2022' AND month='3') OR (year='2022' AND month='2') GROUP BY  1,2,3 ORDER BY  1,2,37
![image](https://user-images.githubusercontent.com/17825769/161323461-b20193a9-658d-4eed-96e6-fc462e3af728.png)

The query above has been found in the CW Logs, which is not working. When i try to fix it directly in Athena query by adding "DATABASE"."TABLE"

> SELECT year, month(line_item_usage_start_date) month, product_product_name AS "Product_Name", sum("line_item_unblended_cost") AS "Cost($)" FROM "athenacurcfn_xxxxxxxxxxxx_c_u_r_hourly_athena"."xxxxxxxxxxxx_cur_hourly_athena" WHERE (year='2022' AND month='4') OR (year='2022' AND month='3') OR (year='2022' AND month='2') GROUP BY  1,2,3 ORDER BY  1,2,3
![image](https://user-images.githubusercontent.com/17825769/161320158-1651a83b-999e-430e-95fb-a1aaa90c6462.png)

The documentation should specify the variable formatting for CUR_DB, which is :
`CUR_DB: '"ATHENA_BD"."ATHENA_Table"'`

**Comment by NK74** [comment]
PR : https://github.com/awslabs/aws-well-architected-labs/pull/503

**Comment by iakov-aws** [comment]
Thanks for the contribution! PR merged. I close the issue.
