### ISSUE TITLE
KPI Dashboard CUR requirements

### ISSUE THREAD

**Issue by darken99** [awslabs/aws-well-architected-labs#527]
Team,

Please check this issue from cid-cmd: https://github.com/aws-samples/aws-cudos-framework-deployment/issues/246
Looks like we're missing documentation around the KPI Dashboard pre-requisites

**Comment by iakov-aws** [comment]
@darken99 please can u review this PR https://github.com/awslabs/aws-well-architected-labs/pull/546

**Comment by iakov-aws** [comment]
Doc updated
