### ISSUE TITLE
Bug: Update the workload architecture - 300 Labs - Sharding/Implement shuffle sharding

### ISSUE THREAD

**Issue by jyidiego** [awslabs/aws-well-architected-labs#554]
In step 7 of the [**Update the workload architecture**](https://www.wellarchitectedlabs.com/reliability/300_labs/300_fault_isolation_with_shuffle_sharding/5_implement_shuffle_sharding/) (this is true with the sharding section as well) the image depicting the button to press, **Create stack**, the actual button should be **Update stack**. The image in step 7 should be replaced with the correct image.

**Comment by TheFuz** [comment]
This has been updated.
