### ISSUE TITLE
DATA COLLECTION MODULES AND TESTING DEPLOYMENT link is broken now

### ISSUE THREAD

**Issue by chettis** [awslabs/aws-well-architected-labs#558]
Hi,
The lab for taos dashboard creation link is broken now. we can't continue with data collection modules lab.
It is redirecting the main page.

**Comment by iakov-aws** [comment]
Here is a tao dashboard deployment link in case you are blocked https://www.wellarchitectedlabs.com/cost/200_labs/200_cloud_intelligence/trusted-advisor-dashboards/dashboards/3_deployment/

**Comment by chettis** [comment]
@iakov-aws This is the link that is broken, when we click on start lab it is going back to the index page instead of the actual lab steps.
https://wellarchitectedlabs.com/cost/300_labs/300_optimization_data_collection/

**Comment by iakov-aws** [comment]
Hi @chettis 
The link was fixed thanks for raising this.
