### ISSUE TITLE
300 Cost Splitting the CUR seems to be missing code in Sub_Account_Split

### ISSUE THREAD

**Issue by sunilgovindankutty** [awslabs/aws-well-architected-labs#57]
```
      def s3_clear_folders() 
       # Get S3 client/object
       client = boto3.client('s3')

    # For each subfolder - in case you have multilpe subfolders, i.e. multilpe accounts/business units to split data out to
    for subfolder in subfolders:
 ```
What is subfolders here?

**Comment by natbesh** [comment]
If you are outputting multiple CURs for multiple linked accounts, each output will be in a separate subfolder.
Refer to the first step, item #4 -  The lab has been designed to allow multiple statements to output to a single bucket, each in a different folder. Create one folder for each Athena statement you will run, a convenient name for the folders is the Account ID of the sub account.
