### ISSUE TITLE
Reliability -> 200_Labs -> Bidirectional_Replication_for_S3: The selected IAM role for replication is not correct.

### ISSUE THREAD

**Issue by lingfengWu88** [awslabs/aws-well-architected-labs#615]
Hi ,

In "Reliability/200_Labs/200_Bidirectional_Replication_for_S3/2_configure_replication.md", the following steps will cause replication failed since these two existing roles don't have sufficient permissions.
- 2.1.11 : For IAM Role select <your-naming-prefix>-S3-Replication-Role-us-east-2 from the search results box
- 2.3.11: For IAM Role select <your-naming-prefix>-S3-Replication-Role-us-west-2 from the search results box

These two steps should be changed as following:
- 2.1.11 : For IAM Role select _create new role_ from search results box
- 2.3.11 : For IAM Role select _create new role_ from search results box

Thanks.

**Comment by RodneyLester** [comment]
This should be fixed with merge #672
