### ISSUE TITLE
Latest Amazon AMI broke httpd24 installation

### ISSUE THREAD

**Issue by jhulfikarali** [awslabs/aws-well-architected-labs#7]
Example given is broken with latest Amazon Linux AMI where it is unable to install `httpd24`. Can you please fix this issue in AMI or move `httpd24` to `httpd`, so it is effective for others. This was kinda embarrassing yesterday during AWS Loft workshop for the presenter as well.

**Reference:**
https://github.com/awslabs/aws-well-architected-labs/blob/master/Security/200%20-%20CloudFront%20with%20WAF%20Protection/Lab%20Guide.md

**Comment by jhulfikarali** [comment]
Update: Looks like it works fine today with Amazon Linux version 1. It would be helpful if someone update the doc with httpd or Amazon Linux version 2

**Comment by benjipotter** [comment]
Thank you @jhulfikarali the instructions are updated now without version number, so it will work in both versions of Amazon Linux.

**Comment by jhulfikarali** [comment]
Great, thanks @benjipotter
