### ISSUE TITLE
typo in one of the screenshots in deploying Dashboards 200 Labs.

### ISSUE THREAD

**Issue by rrdog-aws** [awslabs/aws-well-architected-labs#707]
The image below has a typo:
“List all accounts you whant to group CUR Data from as a comma separated list”

https://www.wellarchitectedlabs.com/Cost/200_Cloud_Intelligence/Images/multi-account/cfn_dash_param_dst_dedicated_3.png?classes=lab_picture_small

I am unable to submit a PL because the /images/ are not available in this repo therefore I cannot commit or put the images from that folder.

the most recent image from console has correct spelling and it should address the typo.

**Comment by iakov-aws** [comment]
https://github.com/awslabs/aws-well-architected-labs#how-to-run-locally
