### ISSUE TITLE
Query DBInstanceIdentifier using aws query option instead of using external program  jq

### ISSUE THREAD

**Issue by mmasoudf** [awslabs/aws-well-architected-labs#79]
The following code is used in the shell script to get the DBInstanceIdentifier:

`aws rds describe-db-instances --profile xxx  | jq -r --arg vpc $vpc '.DBInstances | map(select(.DBSubnetGroup.VpcId==$vpc))[0].DBInstanceIdentifier'`

1- The code eventually assumes that there is only one RDS and returns that one, index 0 (  [0]   ).
2- It expects that jq is installed.

You may use the following aws rds command using --query, which does the same but does not need the 'jq' being installed:

> aws rds describe-db-instances --profile  xxx  --query "[DBInstances[0]] | [?DBSubnetGroup.VpcId=='$vpc'].DBInstanceIdentifier"

**Comment by setheliot** [comment]
sweet!  I will check out it.   - Thanks!

**Comment by setheliot** [comment]
resolved with https://github.com/awslabs/aws-well-architected-labs/commit/9bc426992b2a2966866bdbd2f68fd637846372d0
