### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by kursonsk** [awslabs/aws-well-architected-labs#8]
Hi, guys.

https://awslabs.github.io/aws-well-architected-labs/Reliability/300%20-%20Testing%20for%20Resiliency%20of%20EC2,%20RDS,%20and%20S3/
Links "Lab guide" and "Quickstart" result in 404. Just FYI.

**Comment by natbesh** [comment]
Resolved
This has been fixed - also feel free to use the easier to read html @ http://wellarchitectedlabs.com
