### ISSUE TITLE
Operational Excellence 200 Lab Failing

### ISSUE THREAD

**Issue by dieherna** [awslabs/aws-well-architected-labs#810]
When running the build_application.sh as part of step 1.1 in the Operational Excellence 200 Lab Failing, the cloud formation template walab-ops-sample-application fails to deploy. It fails at deploying at the SyntheticsCanary step with the error below.

`Resource handler returned message: "Invalid request provided: Deprecated runtime version specified. (Service: Synthetics, Status Code: 400, Request ID: 8c5483cf-1442-4b10-a74d-17711858d7df)" (RequestToken: 94a7b401-5e17-2312-38ac-1df3d3f88f24, HandlerErrorCode: InvalidRequest)`

I have tried deploying in both us-west-2 and us-east-1. Fails in both regions.

**Comment by s3rg3d** [comment]
Hi,
Just ran into this issue.
I fixed it by modifying the runtime of SyntheticsCanary in base_app.yml template : 
`RuntimeVersion: syn-nodejs-puppeteer-3.5`

version 3.0 cannot be used anymore

**Comment by sssalim-aws** [comment]
Thank you, waiting for the merge to be un blocked

**Comment by awsdunc** [comment]
PR 828 is merged
