### ISSUE TITLE
Error with Lambda query

### ISSUE THREAD

**Issue by aws-frankbpr** [awslabs/aws-well-architected-labs#821]
When I have tried Lambda query, I received the following error:
"line 35:10: mismatched input '$'. Expecting: '(', 'LATERAL', 'UNNEST', <identifier>, <query>"

I have modified and get a version based on that, can we replace it?

SELECT
bill_payer_account_id,
line_item_usage_account_id,
line_item_product_code,
product_region,
line_item_operation,
      CASE
        WHEN line_item_usage_type LIKE '%Lambda-Edge-GB-Second%' THEN 'Lambda EDGE GB x Sec.'
        WHEN line_item_usage_type LIKE '%Lambda-Edge-Request%' THEN 'Lambda EDGE Requests'
        WHEN line_item_usage_type LIKE '%Lambda-GB-Second%' THEN 'Lambda GB x Sec.'
        WHEN line_item_usage_type LIKE '%Request%' THEN 'Lambda Requests'
        WHEN line_item_usage_type LIKE '%In-Bytes%' THEN 'Data Transfer (IN)'
        WHEN line_item_usage_type LIKE '%Out-Bytes%' THEN 'Data Transfer (Out)'
        WHEN line_item_usage_type LIKE '%Regional-Bytes%' THEN 'Data Transfer (Regional)'
        ELSE 'Other'
      END AS case_line_item_usage_type,
line_item_usage_type,
product_product_family,
product_group,
product_group_description,
line_item_line_item_description,
line_item_line_item_type, 
pricing_term,
pricing_unit,
cast(sum("line_item_usage_amount") AS Decimal(16,2)) as "Usage",
cast(sum("line_item_unblended_cost") AS Decimal(10,2)) as "CostUSD",
SPLIT_PART(line_item_resource_id,':',7) AS "ResourceName",
line_item_resource_id,
      cast(SUM(CASE
        WHEN line_item_line_item_type = 'SavingsPlanCoveredUsage' THEN savings_plan_savings_plan_effective_cost
        WHEN line_item_line_item_type = 'SavingsPlanRecurringFee' THEN savings_plan_total_commitment_to_date - savings_plan_used_commitment
        WHEN line_item_line_item_type = 'SavingsPlanNegation' THEN 0 
        WHEN line_item_line_item_type = 'SavingsPlanUpfrontFee' THEN 0
        WHEN line_item_line_item_type = 'DiscountedUsage' THEN reservation_effective_cost
        WHEN line_item_line_item_type = 'RIFee' THEN reservation_unused_amortized_upfront_fee_for_billing_period + reservation_unused_recurring_fee
        WHEN line_item_line_item_type = 'Fee' AND reservation_reservation_a_r_n <> '' THEN 0
        ELSE line_item_unblended_cost 
      END)AS Decimal(16,2) )AS sum_amortized_cost
FROM CUR12345
WHERE year = '2022' AND month = '11'
    AND product_product_name = 'AWS Lambda'
   AND line_item_line_item_type NOT IN ('Tax','Refund','Credit')
GROUP BY
bill_payer_account_id,
line_item_usage_account_id,
line_item_product_code,
product_region,
line_item_operation,
line_item_usage_type,
product_product_family,
product_group,
product_group_description,
line_item_line_item_description,
line_item_line_item_type,
pricing_term,
pricing_unit,
SPLIT_PART(line_item_resource_id,':',6),
line_item_resource_id
 
HAVING 
  SUM(line_item_unblended_cost) > 0
ORDER BY
  CostUSD DESC;

**Comment by aws-jrmarks** [comment]
Assuming you are talking about https://wellarchitectedlabs.com/cost/300_labs/300_cur_queries/queries/compute/#lambda

If you copy and paste that query without modification, you will get that error:

`"line 35:10: mismatched input '$'. Expecting: '(', 'LATERAL', 'UNNEST', , "`

line 35 is the     `FROM ${table_name}` line

you have to remove all of the `${table_name}` and replace with the actual table name

same with the next line `WHERE ${date_filter}`

per https://wellarchitectedlabs.com/cost/300_labs/300_cur_queries/query_help/


> CUR Query Library uses placeholder variables, indicated by a dollar sign and curly braces (${ }). ${table_name} and ${date_filter} are common placeholder variables used throughout CUR Query Library, which must be replaced before a query will run. For example, if your CUR table is called cur_table and is in a database called cur_db, you would replace ${table_name} with cur_db.cur_table. For ${date_filter}, you have multiple options. See [Filtering by Date](https://wellarchitectedlabs.com/cost/300_labs/300_cur_queries/query_help/#filtering-by-date) in the CUR Query Library Help section for additional details.

**Comment by aws-frankbpr** [comment]
Thanks aws-jrmarks, it worked.
