### ISSUE TITLE
DB1Cluster creation failed due to dependncy issue

### ISSUE THREAD

**Issue by racheliurui** [awslabs/aws-well-architected-labs#85]
https://github.com/awslabs/aws-well-architected-labs/blob/3246f1b88075aa74a2f611fcb925316093c41a74/Security/200_Automated_Deployment_of_EC2_Web_Application/Code/wordpress.yaml#L500
__exception__
```log
DB subnet group 'WebApp1-dbsubnetgroupwp' does not exist. (Service: AmazonRDS; Status Code: 404)
```
__Reason__
Confirmed the issue is caused by dbsubnetgroup being created is using full small letter with name 
webapp1-dbsubnetgroupwp instead of WebApp1-dbsubnetgroupwp. Might be issue with Cloudformation.
__Workaround__
here would be use small letter for name prefix as webapp1 instead of WebApp1

**Comment by benjipotter** [comment]
Thank you @racheliurui  resolved in https://github.com/awslabs/aws-well-architected-labs/commit/ce992527cd15740e2e534e9f9ff6e18665893b81
