### ISSUE TITLE
200_Automated_Deployment_of_EC2_Web_Application:  The template is broken and fails to create the DB cluster because of a case mismatch issue

### ISSUE THREAD

**Issue by jburwell-taos** [awslabs/aws-well-architected-labs#86]
The template is broken and fails to create the DB cluster because of a case mismatch issue.

It appears that the "DB1SubnetGroup" section, which uses "AWS::RDS::DBSubnetGroup" always creates the Subnet Group with the name in all lowercase (regardless of the case of the name given as a parameter).  This causes the following DB1Cluster section to fail due to a case mismatch in the parameter name for "DBSubnetGroupName" having upper-case characters.

A quick fix for this:

```
--- wordpress.yaml      2020-02-06 23:57:44.884194500 -0800
+++ wordpress_fix.yaml  2020-02-07 18:37:43.911347300 -0800
@@ -23,6 +23,11 @@
     Type: String
     Description: The naming prefix for resources created by this template.
     Default: WebApp1
+  NamingPrefixLC:
+    Type: String
+    Description: The naming prefix for resources created by this template in lowercase.
+    Default: webapp1
+    AllowedPattern: '[a-z0-9]*'
   #Imports:
   VPCImportName:
     Type: String
@@ -486,7 +491,7 @@
     #https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbsubnet-group.html
     Properties:
       DBSubnetGroupDescription: !Sub '${NamingPrefix}-SubnetGroup'
-      DBSubnetGroupName: !Sub '${NamingPrefix}-dbsubnetgroupwp'
+      DBSubnetGroupName: !Sub '${NamingPrefixLC}-dbsubnetgroupwp'
       SubnetIds:
         - Fn::ImportValue: !Sub '${VPCImportName}-${VPCImportDB1Subnet1}'
         - Fn::ImportValue: !Sub '${VPCImportName}-${VPCImportDB1Subnet2}'
@@ -499,6 +504,8 @@
               - SubnetGroup
   DB1Cluster:
     Type: AWS::RDS::DBCluster
+    DependsOn:
+      - DB1SubnetGroup
     DeletionPolicy: Delete
     Properties:
       DatabaseName: !Ref DB1Name
```

-- Jim

**Comment by jburwell-taos** [comment]
I wish there were a simple way to do a tolower() in Cloudformation templates, but I couldn't find one which doesn't involve running external code.  Someone please correct me if I'm wrong (BTW, I don't like the mapping method either, just a straight tolower() style capability please).

**Comment by benjipotter** [comment]
Thank you @jburwell-taos resolved in https://github.com/awslabs/aws-well-architected-labs/commit/ce992527cd15740e2e534e9f9ff6e18665893b81
