### ISSUE TITLE
200_Automated_IAM_User_Cleanup: Multiple issues

### ISSUE THREAD

**Issue by jburwell-taos** [awslabs/aws-well-architected-labs#88]
Produced output-template.yaml has several issues:

1. It outputs the python code for the lambda function into the s3 bucket with a path that looks like "<bucket>/824ff77e26a1bdf6ff1928e8c012a592", where apparently the Lamba wants the code in a zip file containing a specifically named filename, "lambda-iam-user-cleanup.py".  This causes issues with Lambda itself not being able to "import" its own function.  The "hash code" style filename caused the registered function to error out.
2. The python code references environment variables (the ones having to do with AWS roles) without the template defining them and their defaults.
3. The template doesn't set up the role with the proper permissions for role-related functions which the script calls on.

**Comment by ByronPogson** [comment]
@jburwell-taos Thank you for the feedback, I have just pushed a fix for points 2 and 3.

In regards to point 1 - can you confirm that you're following the instructions in the lab to deploy this with SAM? If you download that file and append .zip to the end you should be able to see it as an archive with exactly that structure. I've just re-tested the deployment of this and when I go to edit the code in a Lambda editor I see the cleanup.py file.
