### ISSUE TITLE
CloudFormation Template deployments failing

### ISSUE THREAD

**Issue by phumphrey23** [awslabs/aws-well-architected-labs#899]
Receiving CREATE_FAILED and ROLLBACK_IN_PROGRESS status for multiple ec2 and s3 resources when trying to deploy stacks using CloudFormation template for all Disaster Recovery labs.

example error for Hot Standby lab:
![hot-primary](https://user-images.githubusercontent.com/32243763/234117930-50218590-5df8-4dd8-ae88-777a52ab4375.png)

**Comment by jmoran8888** [comment]
This has been fixed with the latest commit on May 1, 2023
