### ISSUE TITLE
[Style] Change hyperlinks colour

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/aws-well-architected-labs#92]
* **Problem**: External links are styled as a variation of `grey` making it difficult to identify. 
* **Suggestion**: Change `accent` colour as primary is already grey

**Comment by dgomesbr** [comment]
Having a hard time with hyperlinks in this variation, a little bit of contrast wouldn't do harm; would also :+1: the use of orange accent instead of blueish/grey.

**Comment by setheliot** [comment]
This was done!  https://github.com/awslabs/aws-well-architected-labs/commit/4737b0c78b7a7309f3ea591b5f87f595402ff2a9
