### ISSUE TITLE
Cost Fundamentals - minor change

### ISSUE THREAD

**Issue by wolruf** [awslabs/aws-well-architected-labs#94]
Hello,
I was checking https://wellarchitectedlabs.com/Cost/Cost_Fundamentals/100_4_Cost_and_Usage_Analysis/Lab_Guide.html and noticed in my console that "Payment history" appears to have been renamed "Orders and Invoices"
![Screen Shot 2020-03-30 at 16 22 15](https://user-images.githubusercontent.com/13536363/77923534-dca09000-72a2-11ea-981a-d023f8048af9.jpg)

**Comment by natbesh** [comment]
updated with lab refresh - resolved

Thanks for the feedback
