### ISSUE TITLE
Not able to deploy Quicksight Cost Intelligence Dashboard from template

### ISSUE THREAD

**Issue by meswaramoorthy** [awslabs/aws-well-architected-labs#962]
When trying to deploy the CID either via the aws sdk & json file route or the cid-cmd deploy route, the deployment fails.
I recieve an error - "Required column 'ri_sp_end_date' is missing in data set" - summary_view dataset.

The CURs data that is being used doesn't have Saving Plan or Reserve Instance.

How to deploy the CID dashboard without saving or RI data?

**Comment by iakov-aws** [comment]
please use cloud formation or cid-cmd tool.
