### ISSUE TITLE
Amortized cost does not take into account market place fees

### ISSUE THREAD

**Issue by swarner1033** [awslabs/aws-well-architected-labs#964]
https://github.com/awslabs/aws-well-architected-labs/blob/main/content/Cost/200_Labs/200_Cloud_Intelligence/Cost%20&%20Usage%20Report%20Dashboards/Dashboards/Code/1_view1.md

```sql
  WHEN (("line_item_line_item_type" = 'Fee') AND ("reservation_reservation_a_r_n" <> '')) THEN 0 ELSE "line_item_unblended_cost" END) "amortized_cost"
```

RI and SP spend is amortized but licensing fees are not. This means that multimillion dollar charges can be lumped into one month.

**Comment by yprikhodko** [comment]
We aware of this, however Cost and Usage Report, which is a source of our dashboards, doesn't have amortized costs for AWS Marketplace products. I believe the same is applicable to Cost Explorer. At this moment the only thing we can do is transfer your feedback to our Cost and Usage Report service team to consider adding amortized costs in similar way to RIs and SPs
