### ISSUE TITLE
Cost Lab idea - EC2 Cloudwatch metrics module

### ISSUE THREAD

**Issue by pbazard** [awslabs/aws-well-architected-labs#965]
Compute optimizer does not list all types of EC2 instances. Add a module for collecting CW metrics for **all** the EC2 instances (on the same model as what exists for RDS).

**Comment by iakov-aws** [comment]
Hi Philippe

 Feel free to contribute a module or check with Compute Optimizer the timeline of the instance types your customer is interested in.

**Comment by iakov-aws** [comment]
Closing for now will track internally
