### ISSUE TITLE
Configure GuardDuty to publish findings to S3 bucket

### ISSUE THREAD

**Issue by khbvirus** [awslabs/aws-well-architected-labs#98]
Hello,
I'm trying to use the stack in 'Security/200_Automated_Deployment_of_Detective_Controls' to configure GuardDuty to send the findings to S3 bucket.
AWS added the feature in late 2019 for GuardDuty to write the findings in S3 bucket in the same account or in another account using a KMS key.

I can achieve that using the API/CLI, but I didn't find a way to include this configuration in my cloudformation stack.
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/guardduty.html#GuardDuty.Client.create_publishing_destination

Is CloudFormation supports this feature right now? If yes how can we moodify the template to add this configuration?

Thank you,

**Comment by benjipotter** [comment]
Thank you for submitting this issue, unfortunately GuardDuty with CloudFormation does not currently support that configuration feature. I will pass it on as a feature request. While we will not modify this lab, as you pointed it out boto3 has support, so you could create a lambda function within the same CloudFormation template to configure this for you.

Regards
