### ISSUE TITLE
Level 300: Optimization Data Collection - Compute Optimizer module 

### ISSUE THREAD

**Issue by felixtheant** [awslabs/aws-well-architected-labs#987]
Hello, 

I have made attempts in deploying the Compute Optimizer Dashboard after deploying the Optimization Data Collection solution however I run into errors when updating the CID stack. 

What I have been able to diagnose is that there are elements missing like glue crawler, SQS queue and Athena tables for the compute optimizer module. I found that in the 'module-compute-optimizer.yaml' template, there was no reference to these elements other than what was in the parameter block. 

The main template, Optimization_Data_Collector.yaml, references the following URL:
https://aws-well-architected-labs.s3.amazonaws.com/Cost/Labs/300_Optimization_Data_Collection/module-compute-optimizer.yaml

When I did a comparison with what is in this repo, it appears that there are elements missing. For reference, I compared with the following:
https://github.com/awslabs/aws-well-architected-labs/blob/576a8ef9bd1e196d90d0f95253d1f219d3d2ba02/static/Cost/300_Optimization_Data_Collection/Code/compute_optimizer.yaml 

As a side note, I ran into some permission issues with Athena and not being able to create a database. I was able to work around it by manually updating the permissions on the 'CidExecRole' IAM role. For reference, here is the error message from the cloudtrail event:
"errorMessage": "User: arn:aws:sts::xxxxxxxxxxxxxx:assumed-role/CidExecRole/CidCustomResourceDashboard is not authorized to perform: glue:CreateDatabase on resource: arn:aws:glue:<region>:xxxxxxxxxxxxxx:catalog because no identity-based policy allows the glue:CreateDatabase action",

Adding 'glue:CreateDatabase"'to the existign policy didn't work, to fix it I applied the following which was only temporary:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "glue:CreateDatabase",
                "glue:UpdateTable",
                "glue:DeleteTable"
            ],
            "Resource": [
    "arn:aws:glue:*:*:table/*/*",
    "arn:aws:glue:*:*:database/*",
    "arn:aws:glue:*:*:catalog"
            ]
        }
    ]
}
```

**Comment by iakov-aws** [comment]
Hello,
Compute Optimizer Module does not contain glue crawler, SQS queue or Athena tables. After installation of data collection module please deploy COD dashboard directly

https://www.wellarchitectedlabs.com/cost/300_labs/300_optimization_data_collection/4_utilize_data/#visualization-of-compute-optimizer-data-with-amazon-quicksight
> You can visualize Compute Optimizer Data with [Compute Optimizer Dashboard](https://wellarchitectedlabs.com/cost/200_labs/200_cloud_intelligence/compute-optimizer-dashboards/). **[Compute Optimizer Dashboard](https://wellarchitectedlabs.com/cost/200_labs/200_cloud_intelligence/compute-optimizer-dashboards/) also deliver Athena Tables and Views**.

**Comment by felixtheant** [comment]
Thanks, I tried that before going into a rabbit hole. 

The error on the CIDS stack I am getting is:
Received response status [FAILED] from custom resource. Message returned: Dataset "compute_optimizer_all_options" (compute_optimizer_all_options) is missing required fields. {'primary_tag': {'expected': 'STRING', 'found': None}, 'secondary_tag': {'expected': 'STRING', 'found': None}}

Tried again just now and same error.

**Comment by iakov-aws** [comment]
Yes I see. 

This error is due to mismatch of version of cfn template 


Please update as follows 

1) update cloud intelligence dashboards stack with a parameter cidVersion=0.2.25
2) update the stack template with latest from the lab
3) install COD dashboard by updating cloud formation parameters 


Totally 3 updates of cloud formation.

**Comment by felixtheant** [comment]
I updated the stack template to the latest in the lab already but the cidVersion number was 0.2.24. 

After updating that part first and then installing the COD Dashboard, all seems well. 

Thanks for the help.
